//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings will be reverted to their defaults. Do you want to continue?.
        /// </summary>
        internal static string AllSettingsWillBeRevertedToTheirDefaults {
            get {
                return ResourceManager.GetString("AllSettingsWillBeRevertedToTheirDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in Geo IP, This option is good choise, but GeoIP data could be not latest and searching take a lot of processor time.
        /// </summary>
        internal static string BuiltInGeoIPDescription {
            get {
                return ResourceManager.GetString("BuiltInGeoIPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in.
        /// </summary>
        internal static string BuiltInGeoIPName {
            get {
                return ResourceManager.GetString("BuiltInGeoIPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find installation url of Proxy Searcher.
        /// </summary>
        internal static string CannotFindInstallationUrl {
            get {
                return ResourceManager.GetString("CannotFindInstallationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update program.
        /// </summary>
        internal static string CannotUpdateProgram {
            get {
                return ResourceManager.GetString("CannotUpdateProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://checkerproxy.net.
        /// </summary>
        internal static string CheckerProxyDotNet {
            get {
                return ResourceManager.GetString("CheckerProxyDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This checker uses online service http://checkerproxy.net. Additionally usage of this service will give you proxy type. Could check HTTP\HTTPS and SOCKS4\SOCKS5 proxies..
        /// </summary>
        internal static string CheckerProxyDotNetDescription {
            get {
                return ResourceManager.GetString("CheckerProxyDotNetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom search.
        /// </summary>
        internal static string DefaultTabName {
            get {
                return ResourceManager.GetString("DefaultTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default type isn&apos;t defined for interface &apos;{0}&apos;.
        /// </summary>
        internal static string DefaultTypeIsntDefinedForInterface {
            get {
                return ResourceManager.GetString("DefaultTypeIsntDefinedForInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear proxy usage history?.
        /// </summary>
        internal static string DoYouReallyWantToClearProxyUsageHistory {
            get {
                return ResourceManager.GetString("DoYouReallyWantToClearProxyUsageHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to apply changes browser &apos;{0}&apos; should be restarted. Do you want to do it now?.
        /// </summary>
        internal static string DoYouWantToRestartBrowser {
            get {
                return ResourceManager.GetString("DoYouWantToRestartBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off.
        /// </summary>
        internal static string DummyGeoIP {
            get {
                return ResourceManager.GetString("DummyGeoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns off Geo IP. It is faster if compare with other options, but it will not give you proxy location.
        /// </summary>
        internal static string DummyGeoIPDescription {
            get {
                return ResourceManager.GetString("DummyGeoIPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has happened. Press Details button for details.
        /// </summary>
        internal static string ErrorHasHappened {
            get {
                return ResourceManager.GetString("ErrorHasHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/p/proxysearcher/discussion/yourfeedback/.
        /// </summary>
        internal static string FeedbackLink {
            get {
                return ResourceManager.GetString("FeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        internal static string Firefox {
            get {
                return ResourceManager.GetString("Firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /firstrun.
        /// </summary>
        internal static string FirstRunArgument {
            get {
                return ResourceManager.GetString("FirstRunArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is in progress.  {0} proxies have been found..
        /// </summary>
        internal static string FoundProxiesFormat {
            get {
                return ResourceManager.GetString("FoundProxiesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://google.com.
        /// </summary>
        internal static string GoogleDotCom {
            get {
                return ResourceManager.GetString("GoogleDotCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses http://google.com site for proxy searching. If you cannot open http://google.com from browser then use other type of search engine.
        /// </summary>
        internal static string GoogleEngineDescription {
            get {
                return ResourceManager.GetString("GoogleEngineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid has no sorting.
        /// </summary>
        internal static string GridHasNoSorting {
            get {
                return ResourceManager.GetString("GridHasNoSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/projects/proxysearcher/.
        /// </summary>
        internal static string HomePageDeveloperLink {
            get {
                return ResourceManager.GetString("HomePageDeveloperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/.
        /// </summary>
        internal static string HomePageLink {
            get {
                return ResourceManager.GetString("HomePageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet explorer.
        /// </summary>
        internal static string InternetExplorer {
            get {
                return ResourceManager.GetString("InternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Count {0}.
        /// </summary>
        internal static string JobCountFormat {
            get {
                return ResourceManager.GetString("JobCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://sourceforge.net/p/proxysearcher/blog/.
        /// </summary>
        internal static string NewsLink {
            get {
                return ResourceManager.GetString("NewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opera.
        /// </summary>
        internal static string Opera {
            get {
                return ResourceManager.GetString("Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Url.
        /// </summary>
        internal static string ProxyCheckerByUrl {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy checker downloads content of specified url with and without proxy. If contents are similar then proxy is valid and will be returned by checker. This method is slower if compare with checker by IP:Port, but it filters better. If this checker don&apos;t return any results try to change accuracy, probably page&apos;s content is too dynamic. Because of downloading page content this checker takes internet traffic..
        /// </summary>
        internal static string ProxyCheckerByUrlDescription {
            get {
                return ResourceManager.GetString("ProxyCheckerByUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Searcher 1.4.
        /// </summary>
        internal static string ProxySearcherVersion {
            get {
                return ResourceManager.GetString("ProxySearcherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row style &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string RowStyleIsNotSupported {
            get {
                return ResourceManager.GetString("RowStyleIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is cancelled on user request.
        /// </summary>
        internal static string SearchIsCancelledOnUserRequest {
            get {
                return ResourceManager.GetString("SearchIsCancelledOnUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is finished. {0} proxies was found.
        /// </summary>
        internal static string SearchIsFinishedProxiesWasFound {
            get {
                return ResourceManager.GetString("SearchIsFinishedProxiesWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is finished. No proxy was found. Change search query and try again.
        /// </summary>
        internal static string SearchIsFinishedProxiesWasNotFound {
            get {
                return ResourceManager.GetString("SearchIsFinishedProxiesWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /shutdown.
        /// </summary>
        internal static string ShutdownArgument {
            get {
                return ResourceManager.GetString("ShutdownArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By IP:Port.
        /// </summary>
        internal static string SimpleProxyChecker {
            get {
                return ResourceManager.GetString("SimpleProxyChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This simple checker sees if ip address of candidate is alive and port is opened. Can be used for any proxy type searching. It is fast because it don&apos;t require any external services. It cannot check if candidate is workable proxy therefore it could return non-workable proxies. Also this checker cannot determine type of proxy.
        /// </summary>
        internal static string SimpleProxyCheckerDescription {
            get {
                return ResourceManager.GetString("SimpleProxyCheckerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://google.com.
        /// </summary>
        internal static string SimpleSite {
            get {
                return ResourceManager.GetString("SimpleSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort type by &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string SortTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SortTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/p/proxysearcher/tickets/.
        /// </summary>
        internal static string TicketsLink {
            get {
                return ResourceManager.GetString("TicketsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string Uninstalling {
            get {
                return ResourceManager.GetString("Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version of Proxy Searcher is avaliable. Do you want to get it now?.
        /// </summary>
        internal static string UpdateIsReadyToInstall {
            get {
                return ResourceManager.GetString("UpdateIsReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait until current operation is finished.
        /// </summary>
        internal static string WaitUntilCurrentOperationIsFinished {
            get {
                return ResourceManager.GetString("WaitUntilCurrentOperationIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.webservicex.net/geoipservice.asmx.
        /// </summary>
        internal static string WebServiceNetGeoIPService {
            get {
                return ResourceManager.GetString("WebServiceNetGeoIPService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses http://www.webservicex.net/geoipservice.asmx service as Geo IP. If you cannot open http://www.webservicex.net/geoipservice.asmx from browser then use other type of Geo IP.
        /// </summary>
        internal static string WebServiceNetGeoIPServiceDescription {
            get {
                return ResourceManager.GetString("WebServiceNetGeoIPServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should clear value before set new one.
        /// </summary>
        internal static string YouShouldClearValueBeforeSetNewOne {
            get {
                return ResourceManager.GetString("YouShouldClearValueBeforeSetNewOne", resourceCulture);
            }
        }
    }
}
