//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type hides your ip, but proxy usage could be detected easily. 
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string AnonymousDetails {
            get {
                return ResourceManager.GetString("AnonymousDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download content of &apos;{0}&apos;. In order to fix this issue go to Tools-&gt;Properties and change proxy checker url to valid one.
        /// </summary>
        internal static string CannotDownloadContent {
            get {
                return ResourceManager.GetString("CannotDownloadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot verify.
        /// </summary>
        internal static string CannotVerify {
            get {
                return ResourceManager.GetString("CannotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we cannot detect type of this proxy. 
        ///Probably it is offline or blocks our test service.
        ///You still able to use this proxy on your own risk.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string CannotVerifyDetails {
            get {
                return ResourceManager.GetString("CannotVerifyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes content.
        /// </summary>
        internal static string ChangesContent {
            get {
                return ResourceManager.GetString("ChangesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During detection type of this proxy downloaded content was changed . 
        ///Most for all this proxy cannot be used free, it could infect your viruses 
        ///or provide some commercial. Try to avoid usage proxy of this type.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string ChangesContentDetails {
            get {
                return ResourceManager.GetString("ChangesContentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Anonymous.
        /// </summary>
        internal static string HighAnonymous {
            get {
                return ResourceManager.GetString("HighAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type hides your ip and proxy usage cannot be detected easily. 
        ///Some methods could detect proxy usage , but they dont give 100% guarantee 
        ///that proxy usage will be detected. It is safest type of public proxy.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string HighAnonymousDetails {
            get {
                return ResourceManager.GetString("HighAnonymousDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23154081-CFE8-4AC3-A530-142CB55C486D.
        /// </summary>
        internal static string ProxyTypeDetectorGuid {
            get {
                return ResourceManager.GetString("ProxyTypeDetectorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/DetectProxyType.php?param={0}.
        /// </summary>
        internal static string ProxyTypeDetectorUrl {
            get {
                return ResourceManager.GetString("ProxyTypeDetectorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/Bandwidth.
        /// </summary>
        internal static string SpeedTestUrl {
            get {
                return ResourceManager.GetString("SpeedTestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type don&apos;t hide your ip and proxy usage could be detected easily. 
        ///It is worst proxy type. Never transfer secure data with public proxy..
        /// </summary>
        internal static string TransparentDetails {
            get {
                return ResourceManager.GetString("TransparentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned Off.
        /// </summary>
        internal static string TurnedOffGeoIP {
            get {
                return ResourceManager.GetString("TurnedOffGeoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for test.
        /// </summary>
        internal static string UncheckedDetails {
            get {
                return ResourceManager.GetString("UncheckedDetails", resourceCulture);
            }
        }
    }
}
