//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type hides your ip, but proxy usage could be detected easily. 
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string AnonymousDetails {
            get {
                return ResourceManager.GetString("AnonymousDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download content of &apos;{0}&apos;. Probably you don&apos;t have internet connection or &apos;{0}&apos; is blocked for your network. If it&apos;s blocked then go to Tools-&gt;Properties and change proxy checker &apos;By Url&apos; to &apos;By Url and Keywords&apos; (this checked type is espessially for blocked sites)..
        /// </summary>
        internal static string CannotDownloadContent {
            get {
                return ResourceManager.GetString("CannotDownloadContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot verify.
        /// </summary>
        internal static string CannotVerify {
            get {
                return ResourceManager.GetString("CannotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we cannot detect type of this proxy. 
        ///Probably it is offline or blocks our test service.
        ///You still able to use this proxy on your own risk.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string CannotVerifyDetails {
            get {
                return ResourceManager.GetString("CannotVerifyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes content.
        /// </summary>
        internal static string ChangesContent {
            get {
                return ResourceManager.GetString("ChangesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During detection type of this proxy downloaded content was changed . 
        ///Most for all this proxy cannot be used free, it could infect your viruses 
        ///or provide some commercial. Try to avoid usage proxy of this type.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string ChangesContentDetails {
            get {
                return ResourceManager.GetString("ChangesContentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Anonymous.
        /// </summary>
        internal static string HighAnonymous {
            get {
                return ResourceManager.GetString("HighAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type hides your ip and proxy usage cannot be detected easily. 
        ///Some methods could detect proxy usage , but they dont give 100% guarantee 
        ///that proxy usage will be detected. It is safest type of public proxy.
        ///Never transfer secure data with public proxy..
        /// </summary>
        internal static string HighAnonymousDetails {
            get {
                return ResourceManager.GetString("HighAnonymousDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        internal static string HttpProxyType {
            get {
                return ResourceManager.GetString("HttpProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid http response from socks proxy.
        /// </summary>
        internal static string InvalidHttpResponseFromSocksProxy {
            get {
                return ResourceManager.GetString("InvalidHttpResponseFromSocksProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ipregex&gt;.
        /// </summary>
        internal static string IPRegexKey {
            get {
                return ResourceManager.GetString("IPRegexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;portregex&gt;.
        /// </summary>
        internal static string PortRegexKey {
            get {
                return ResourceManager.GetString("PortRegexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy property cannot be null..
        /// </summary>
        internal static string ProxyPropertyCannotBeNull {
            get {
                return ResourceManager.GetString("ProxyPropertyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23154081-CFE8-4AC3-A530-142CB55C486D.
        /// </summary>
        internal static string ProxyTypeDetectorGuid {
            get {
                return ResourceManager.GetString("ProxyTypeDetectorGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/DetectProxyTypeV2.php?ip={0}&amp;port={1}&amp;type={2}&amp;param={3}.
        /// </summary>
        internal static string ProxyTypeDetectorUrl {
            get {
                return ResourceManager.GetString("ProxyTypeDetectorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks v4.
        /// </summary>
        internal static string Socks4 {
            get {
                return ResourceManager.GetString("Socks4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type is working on transport layer of TCP/IP protocol and supports v4 of Socks proxy.
        /// </summary>
        internal static string Socks4Details {
            get {
                return ResourceManager.GetString("Socks4Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socks v5.
        /// </summary>
        internal static string Socks5 {
            get {
                return ResourceManager.GetString("Socks5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type is working on transport layer of TCP/IP protocol and supports v5 of Socks proxy without authentication.
        /// </summary>
        internal static string Socks5Details {
            get {
                return ResourceManager.GetString("Socks5Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS.
        /// </summary>
        internal static string SocksProxyType {
            get {
                return ResourceManager.GetString("SocksProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://proxysearcher.sourceforge.net/Bandwidth.
        /// </summary>
        internal static string SpeedTestUrl {
            get {
                return ResourceManager.GetString("SpeedTestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many redirects was requested by server.
        /// </summary>
        internal static string TooManyRedirectsWasRequestedByServer {
            get {
                return ResourceManager.GetString("TooManyRedirectsWasRequestedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This proxy type don&apos;t hide your ip and proxy usage could be detected easily. 
        ///It is worst proxy type. Never transfer secure data with public proxy..
        /// </summary>
        internal static string TransparentDetails {
            get {
                return ResourceManager.GetString("TransparentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve proxy hostname &apos;{0}&apos; to a valid IP address..
        /// </summary>
        internal static string UnableToResolveProxyHostnameFormat {
            get {
                return ResourceManager.GetString("UnableToResolveProxyHostnameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string Unchecked {
            get {
                return ResourceManager.GetString("Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for test.
        /// </summary>
        internal static string UncheckedDetails {
            get {
                return ResourceManager.GetString("UncheckedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported http proxy type.
        /// </summary>
        internal static string UnsupportedHttpProxyType {
            get {
                return ResourceManager.GetString("UnsupportedHttpProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported socks proxy type.
        /// </summary>
        internal static string UnsupportedSocksProxyType {
            get {
                return ResourceManager.GetString("UnsupportedSocksProxyType", resourceCulture);
            }
        }
    }
}
