//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxySearch.Console.Code.GoogleAnalytics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GAResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GAResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProxySearch.Console.Code.GoogleAnalytics.GAResources", typeof(GAResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA-43171311-1.
        /// </summary>
        internal static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tid.
        /// </summary>
        internal static string AccountIdKey {
            get {
                return ResourceManager.GetString("AccountIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Searcher.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        internal static string ApplicationNameKey {
            get {
                return ResourceManager.GetString("ApplicationNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cid.
        /// </summary>
        internal static string ClientIdKey {
            get {
                return ResourceManager.GetString("ClientIdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.google-analytics.com/collect.
        /// </summary>
        internal static string CollectUrl {
            get {
                return ResourceManager.GetString("CollectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ea.
        /// </summary>
        internal static string EventActionKey {
            get {
                return ResourceManager.GetString("EventActionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ec.
        /// </summary>
        internal static string EventCategoryKey {
            get {
                return ResourceManager.GetString("EventCategoryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exd.
        /// </summary>
        internal static string ExceptionKey {
            get {
                return ResourceManager.GetString("ExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string HitTypeKey {
            get {
                return ResourceManager.GetString("HitTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd.
        /// </summary>
        internal static string PageNameKey {
            get {
                return ResourceManager.GetString("PageNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to av.
        /// </summary>
        internal static string ProgramVersionKey {
            get {
                return ResourceManager.GetString("ProgramVersionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ProtocolVersionFirst {
            get {
                return ResourceManager.GetString("ProtocolVersionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string ProtocolVersionKey {
            get {
                return ResourceManager.GetString("ProtocolVersionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        internal static string ScreenResoultion {
            get {
                return ResourceManager.GetString("ScreenResoultion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.
        /// </summary>
        internal static string UserLanguage {
            get {
                return ResourceManager.GetString("UserLanguage", resourceCulture);
            }
        }
    }
}
